---
  - name: start php-fpm
    systemd:
      name: php7.2-fpm
      state: started
      enabled: yes
  - name: restart php-fpm
    systemd:
      name: php7.2-fpm
      state: restarted




# handlers file for php
